apiVersion: apps/v1
kind: Deployment
metadata:
  name: sajal-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sajal-springboot
  template:
    metadata:
      labels:
        app: sajal-springboot
    spec:
      containers:
        - name: springboot
          image: sajalra/global:dockerkub
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: sajal-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sajal-springboot
